// <auto-generated />
using System;
using GymManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymManagement.Data.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260418153943_SeedUtilizadores")]
    partial class SeedUtilizadores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymManagement.Models.Entities.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("int");

                    b.Property<int>("InstrutorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlanoTreinoId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrutorId");

                    b.HasIndex("PlanoTreinoId");

                    b.HasIndex("SalaId");

                    b.ToTable("Aulas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            DataHora = new DateTime(2025, 6, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DuracaoMinutos = 60,
                            InstrutorId = 1,
                            Nome = "Musculação Avançada",
                            PlanoTreinoId = 1,
                            SalaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            DataHora = new DateTime(2025, 6, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            DuracaoMinutos = 45,
                            InstrutorId = 2,
                            Nome = "Yoga Relaxante",
                            PlanoTreinoId = 2,
                            SalaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            DataHora = new DateTime(2025, 6, 3, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            DuracaoMinutos = 50,
                            InstrutorId = 3,
                            Nome = "Spinning Intensivo",
                            PlanoTreinoId = 3,
                            SalaId = 3
                        },
                        new
                        {
                            Id = 4,
                            Ativa = true,
                            DataHora = new DateTime(2025, 6, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DuracaoMinutos = 45,
                            InstrutorId = 2,
                            Nome = "Yoga Manhã",
                            PlanoTreinoId = 2,
                            SalaId = 2
                        });
                });

            modelBuilder.Entity("GymManagement.Models.Entities.Frequencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Entrada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Saida")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Frequencias");
                });

            modelBuilder.Entity("GymManagement.Models.Entities.InscricaoAula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AulaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.HasIndex("UtilizadorId", "AulaId")
                        .IsUnique();

                    b.ToTable("Inscricoes");
                });

            modelBuilder.Entity("GymManagement.Models.Entities.Instrutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instrutores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Email = "carlos@gym.pt",
                            Especialidade = "Musculação",
                            Nome = "Carlos Silva",
                            Telefone = "961000001"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Email = "ana@gym.pt",
                            Especialidade = "Yoga",
                            Nome = "Ana Ferreira",
                            Telefone = "961000002"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Email = "rui@gym.pt",
                            Especialidade = "Spinning",
                            Nome = "Rui Costa",
                            Telefone = "961000003"
                        });
                });

            modelBuilder.Entity("GymManagement.Models.Entities.PlanoTreino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PlanosTreino");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Treino de força e hipertrofia muscular",
                            DuracaoMinutos = 60,
                            Nivel = 1,
                            Nome = "Musculação"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Relaxamento, flexibilidade e equilíbrio",
                            DuracaoMinutos = 45,
                            Nivel = 0,
                            Nome = "Yoga"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cardio intensivo em bicicleta estática",
                            DuracaoMinutos = 50,
                            Nivel = 2,
                            Nome = "Spinning"
                        });
                });

            modelBuilder.Entity("GymManagement.Models.Entities.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            CapacidadeMaxima = 20,
                            Descricao = "Sala de musculação e pesos",
                            Nome = "Sala A"
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            CapacidadeMaxima = 15,
                            Descricao = "Sala de yoga e pilates",
                            Nome = "Sala B"
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            CapacidadeMaxima = 25,
                            Descricao = "Sala de spinning e cardio",
                            Nome = "Sala C"
                        });
                });

            modelBuilder.Entity("GymManagement.Models.Entities.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilizadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataRegisto = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gym.pt",
                            Nome = "Administrador",
                            PasswordHash = "$2a$11$QiCE/ThU0aoCspQ8gp7Ht.jSi6eEk/VCaMTZiWnDq1rY2z.dprllu",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataRegisto = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cliente@gym.pt",
                            Nome = "João Cliente",
                            PasswordHash = "$2a$11$jO299jjkJxdXvdVc8V1/ueLFMSeI2amruLTor4oG6meWhtNIx9ow6",
                            Role = 1,
                            Telefone = "912345678"
                        });
                });

            modelBuilder.Entity("GymManagement.Models.Entities.Aula", b =>
                {
                    b.HasOne("GymManagement.Models.Entities.Instrutor", "Instrutor")
                        .WithMany("Aulas")
                        .HasForeignKey("InstrutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymManagement.Models.Entities.PlanoTreino", "PlanoTreino")
                        .WithMany("Aulas")
                        .HasForeignKey("PlanoTreinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymManagement.Models.Entities.Sala", "Sala")
                        .WithMany("Aulas")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrutor");

                    b.Navigation("PlanoTreino");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("GymManagement.Models.Entities.Frequencia", b =>
                {
                    b.HasOne("GymManagement.Models.Entities.Utilizador", "Utilizador")
                        .WithMany("Frequencias")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("GymManagement.Models.Entities.InscricaoAula", b =>
                {
                    b.HasOne("GymManagement.Models.Entities.Aula", "Aula")
                        .WithMany("Inscricoes")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManagement.Models.Entities.Utilizador", "Utilizador")
                        .WithMany("Inscricoes")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("GymManagement.Models.Entities.Aula", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("GymManagement.Models.Entities.Instrutor", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("GymManagement.Models.Entities.PlanoTreino", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("GymManagement.Models.Entities.Sala", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("GymManagement.Models.Entities.Utilizador", b =>
                {
                    b.Navigation("Frequencias");

                    b.Navigation("Inscricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
